version: '3'

includes:
  common:
    taskfile: ./build/Taskfile.yml
    optional: true

vars:
  APP_NAME: cmdex
  BIN_DIR: bin
  VITE_PORT: 9245

tasks:
  darwin:build:
    summary: Build for Darwin/macOS
    cmds:
      - task: common:build
        vars:
          DEV: "false"
          OUTPUT: "{{.BIN_DIR}}/{{.APP_NAME}}"

  build:
    summary: Builds the application for current platform
    cmds:
      - task: darwin:build

  build:frontend:
    dir: frontend
    deps:
      - install:deps
      - generate:bindings
    cmds:
      - pnpm run build

  install:deps:
    dir: frontend
    cmds:
      - pnpm install

  generate:bindings:
    cmds:
      - wails3 generate bindings -clean=true

  dev:
    summary: Run in development mode
    cmds:
      - wails3 dev

  run:
    summary: Run the built binary
    cmds:
      - ./{{.BIN_DIR}}/{{.APP_NAME}}
