// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * NullString represents a string that may be null.
 * NullString implements the [Scanner] interface so
 * it can be used as a scan destination:
 * 
 * 	var s NullString
 * 	err := db.QueryRow("SELECT name FROM foo WHERE id=?", id).Scan(&s)
 * 	...
 * 	if s.Valid {
 * 	   // use s.String
 * 	} else {
 * 	   // NULL value
 * 	}
 */
export class NullString {
    /**
     * Creates a new NullString instance.
     * @param {Partial<NullString>} [$$source = {}] - The source object to create the NullString.
     */
    constructor($$source = {}) {
        if (!("String" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["String"] = "";
        }
        if (!("Valid" in $$source)) {
            /**
             * Valid is true if String is not NULL
             * @member
             * @type {boolean}
             */
            this["Valid"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NullString instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NullString}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NullString(/** @type {Partial<NullString>} */($$parsedSource));
    }
}
