// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SuggestionService feeds the terminal's Warp-style autosuggestions: as the
 * user types at the shell prompt, Terminal.tsx shows the most recent matching
 * command as inline ghost text and lists further matches (shell history plus
 * saved Cmdex commands) in a menu under the cursor. The saved-command half
 * already lives in the frontend's state; this service supplies the other
 * half by reading the session shell's own history file (shell_history.go).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CompleteCommands lists executables on the session shell's PATH plus that
 * shell's builtins whose names start with prefix (case-insensitive), sorted,
 * at most maxCommandCompletions. Read-style: never errors.
 * @param {string} sessionID
 * @param {string} prefix
 * @returns {$CancellablePromise<string[]>}
 */
export function CompleteCommands(sessionID, prefix) {
    return $Call.ByID(1899960052, sessionID, prefix).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CompletePath lists the entries of the directory named by partial (relative
 * to the session's current working directory, "~" and absolute paths
 * honored) whose names start with partial's last path segment. dirsOnly
 * restricts the list to directories (cd). Hidden entries are included only
 * when the segment itself starts with ".". Read-style: never errors, at most
 * maxPathCompletions entries, directories first.
 * @param {string} sessionID
 * @param {string} partial
 * @param {boolean} dirsOnly
 * @returns {$CancellablePromise<$models.PathCompletion[]>}
 */
export function CompletePath(sessionID, partial, dirsOnly) {
    return $Call.ByID(3142581141, sessionID, partial, dirsOnly).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetShellHistory returns the most recent distinct single-line commands from
 * the history file of the shell running in sessionID ("" = the active
 * session), newest first. limit <= 0 uses shellHistoryDefaultLimit; larger
 * values are capped at shellHistoryMaxLimit. Like the other read-style bound
 * methods it never surfaces an error to the frontend: on any failure it logs
 * and returns an empty slice, and a shell with no readable history (cmd.exe,
 * or a history file that doesn't exist yet) is simply empty.
 * @param {string} sessionID
 * @param {number} limit
 * @returns {$CancellablePromise<string[]>}
 */
export function GetShellHistory(sessionID, limit) {
    return $Call.ByID(1701603833, sessionID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.PathCompletion.createFrom;
const $$createType2 = $Create.Array($$createType1);
