// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCategory(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateCategory'](arg1, arg2, arg3);
}

export function CreateCommand(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateCommand'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteCommand(arg1) {
  return window['go']['main']['App']['DeleteCommand'](arg1);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetCommands() {
  return window['go']['main']['App']['GetCommands']();
}

export function GetCommandsByCategory(arg1) {
  return window['go']['main']['App']['GetCommandsByCategory'](arg1);
}

export function GetVariables(arg1) {
  return window['go']['main']['App']['GetVariables'](arg1);
}

export function RunCommand(arg1, arg2) {
  return window['go']['main']['App']['RunCommand'](arg1, arg2);
}

export function SearchCommands(arg1) {
  return window['go']['main']['App']['SearchCommands'](arg1);
}

export function UpdateCategory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateCategory'](arg1, arg2, arg3, arg4);
}

export function UpdateCommand(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateCommand'](arg1, arg2, arg3, arg4, arg5, arg6);
}
