// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateCategory(arg1:string,arg2:string,arg3:string):Promise<main.Category>;

export function CreateCommand(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<main.Command>;

export function DeleteCategory(arg1:string):Promise<void>;

export function DeleteCommand(arg1:string):Promise<void>;

export function GetCategories():Promise<Array<main.Category>>;

export function GetCommands():Promise<Array<main.Command>>;

export function GetCommandsByCategory(arg1:string):Promise<Array<main.Command>>;

export function GetVariables(arg1:string):Promise<Array<main.VariablePrompt>>;

export function RunCommand(arg1:string,arg2:Record<string, string>):Promise<main.ExecutionResult>;

export function SearchCommands(arg1:string):Promise<Array<main.Command>>;

export function UpdateCategory(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.Category>;

export function UpdateCommand(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Array<string>):Promise<main.Command>;
