// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearExecutionHistory():Promise<void>;

export function CreateCategory(arg1:string,arg2:string,arg3:string):Promise<main.Category>;

export function CreateCommand(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>,arg6:Array<main.VariableDefinition>):Promise<main.Command>;

export function DeleteCategory(arg1:string):Promise<void>;

export function DeleteCommand(arg1:string):Promise<void>;

export function DeletePreset(arg1:string,arg2:string):Promise<void>;

export function ExportCommands(arg1:Array<string>):Promise<void>;

export function GetAvailableTerminals():Promise<Array<main.TerminalInfo>>;

export function GetCategories():Promise<Array<main.Category>>;

export function GetCommands():Promise<Array<main.Command>>;

export function GetCommandsByCategory(arg1:string):Promise<Array<main.Command>>;

export function GetExecutionHistory():Promise<Array<main.ExecutionRecord>>;

export function GetPresets(arg1:string):Promise<Array<main.VariablePreset>>;

export function GetScriptBody(arg1:string):Promise<string>;

export function GetScriptContent(arg1:string):Promise<string>;

export function GetSettings():Promise<main.AppSettings>;

export function GetVariables(arg1:string):Promise<Array<main.VariablePrompt>>;

export function ImportCommands():Promise<Array<main.Command>>;

export function RenameCommand(arg1:string,arg2:string):Promise<main.Command>;

export function ReorderCommand(arg1:string,arg2:number,arg3:string):Promise<Array<main.Command>>;

export function ReorderPresets(arg1:string,arg2:Array<string>):Promise<void>;

export function ResetAllData():Promise<void>;

export function RunCommand(arg1:string,arg2:Record<string, string>):Promise<main.ExecutionRecord>;

export function RunInTerminal(arg1:string,arg2:Record<string, string>):Promise<void>;

export function SavePreset(arg1:string,arg2:string,arg3:Record<string, string>):Promise<main.VariablePreset>;

export function SaveThemeTemplate():Promise<void>;

export function SearchCommands(arg1:string):Promise<Array<main.Command>>;

export function SetSettings(arg1:string,arg2:string):Promise<void>;

export function UpdateCategory(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.Category>;

export function UpdateCommand(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Array<string>,arg7:Array<main.VariableDefinition>):Promise<main.Command>;

export function UpdatePreset(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>):Promise<main.VariablePreset>;
